config/routes.rb
Codegrate::Application.routes.draw do
  
  resources :repositories

  root :to => "dashboard#index"
  
  match "data" => "dashboard#show"
  match "authors" => "authors#index"
  match "scores" => "scores#index"
  

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  
  SUPPORTED_REPOSITORY_TYPES = ['git']
  
  after_save :request_refresh
  
  def request_refresh
    RepositoryProcessor.request_refresh(self.uri)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.xml
  def index
    success = false
    @repositories = Repository.all
    if @repositories != nil
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @repositories }
      end
    else
      respond_to do |format|
        format.html # index.html.erb
        # TODO: need better response
        format.xml  { render :xml => '' }
      end
    end
  end

  # GET /repositories/1
  # GET /repositories/1.xml
  def show
    success = false
    @repository = Repository.find(params[:id])
    if @repository != nil
      success = @repository.save
    end
    
    if success
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @repository }
      end
    else
      respond_to do |format|
        format.html # show.html.erb
        # TODO: need better response
        format.xml  { render :xml => '' }
      end
    end
  end

  # GET /repositories/new
  # GET /repositories/new.xml
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.xml
  def create
    success = false
    @repository = Repository.new(params[:repository])
    if @repository != nil
      success = @repository.save
    end

    respond_to do |format|
      if success
        format.html { redirect_to(@repository, :notice => 'Repository was successfully created.') }
        format.xml  { head :ok }
      elsif @repository != nil
        format.html { render :action => "new" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }        
      else
        format.html { render :action => "index" }
        # TODO: need better response
        format.xml  { render :xml => '', :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.xml
  def update
    success = false
    @repository = Repository.find(params[:id])
    if @repository != nil
      success = @repository.update_attributes(params[:repository])
    end
    
    respond_to do |format|
      if success
        format.html { redirect_to(@repository, :notice => 'Repository was successfully updated.') }
        format.xml  { head :ok }
      elsif @repository != nil
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }        
      else
        format.html { render :action => "index" }
        # TODO: need better response
        format.xml  { render :xml => '', :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.xml
  def destroy
    @repository = Repository.find(params[:id])
    if @repository != nil
      Score.find_by_repository_id(@repository[:id]).each do |score|
        Score.delete(score)
      end
      @repository.destroy
    end

    respond_to do |format|
      format.html { redirect_to(repositories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repository_type %><br />
    <%= f.select(:repository_type, options_for_select(Repository::SUPPORTED_REPOSITORY_TYPES.collect {|supported_repository_type| [supported_repository_type.humanize, supported_repository_type]})) %>
  </div>
  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Codegrate - Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Codegrate - Manage Repositories</h1>

<table class="cg-table">
  <tr>
	<th>Id</th>
    <th>Name</th>
    <th>Repository type</th>
    <th>Uri</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repositories.each do |repository| %>
  <tr>
	<td><%= repository[:id] %></td>
    <td><%= repository.name %></td>
    <td><%= repository.repository_type %></td>
    <td><%= repository.uri %></td>
    <td><%= link_to 'Show', repository %></td>
    <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
    <td><%= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>Codegrate - New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<h1>Codegrate - Showing repository</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repository.name %>
</p>

<p>
  <b>Repository type:</b>
  <%= @repository.repository_type %>
</p>

<p>
  <b>Uri:</b>
  <%= @repository.uri %>
</p>


<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>